project_id = "orybzmkhccrqmjuvioln"

[functions.send-email]
verify_jwt = false

[functions.webrtc-signal]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = true

[functions.manage-user-credentials]
verify_jwt = true

[functions.cleanup-old-messages]
verify_jwt = false

[functions.cleanup-stale-sessions]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
