project_id = "orybzmkhccrqmjuvioln"

[functions.send-email]
verify_jwt = true

[functions.email-notifications]
verify_jwt = true

[functions.webrtc-signal]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = true

[functions.manage-user-credentials]
verify_jwt = true

[functions.cleanup-old-messages]
verify_jwt = true

[functions.cleanup-stale-sessions]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.signup-organization]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[edge_runtime]
policy = "per_worker"
